# Generated by Django 4.1 on 2022-09-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='datas',
            new_name='data',
        ),
    ]
