# Generated by Django 4.1 on 2022-09-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_datas_dashboard_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_element', models.CharField(max_length=100)),
                ('location_element', models.CharField(max_length=100)),
            ],
        ),
    ]
