# Generated by Django 4.1 on 2022-10-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_fake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('mess', models.CharField(max_length=100)),
            ],
        ),
    ]
