# Generated by Django 4.1 on 2022-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_fmain_notepad_alter_fake_location_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fake',
            name='location_element',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Fmain',
        ),
    ]
