# Generated by Django 4.1 on 2022-10-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_fake_location_element_delete_fmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='fake',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.dashboard'),
        ),
    ]
