# Generated by Django 4.1 on 2022-11-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_fake_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('time_posted', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
    ]
